Repository cloudevents/sdk-java, pull requests merged in 2020-12, with the labels that each got.

#309 Simplify the Reader/Writer implementations, reducing the knowledge of spec details
  amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpMessageWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventContextReader.java
  api/src/main/java/io/cloudevents/rw/CloudEventContextWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventWriter.java
  core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventContextReaderAdapter.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
  core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
  core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  examples/amqp-proton/src/main/java/io/cloudevents/examples/amqp/vertx/AmqpClient.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
  http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageWriter.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSClientMessageWriter.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageWriter.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxHttpServerResponseMessageWriterImpl.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxWebClientRequestMessageWriterImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/BaseKafkaMessageWriterImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaProducerMessageWriterImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaSerializerMessageWriterImpl.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageWriter.java
Labels: enhancement

#315 Add support for Message<CloudEvent>
  spring/pom.xml
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventHeaderUtils.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventMessageConverter.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventsHeaders.java
  spring/src/main/java/io/cloudevents/spring/messaging/MessageBinaryMessageReader.java
  spring/src/main/java/io/cloudevents/spring/messaging/MessageBuilderMessageWriter.java
  spring/src/main/java/io/cloudevents/spring/messaging/package-info.java
  spring/src/test/java/io/cloudevents/spring/messaging/CloudEventHeaderUtilsTests.java
  spring/src/test/java/io/cloudevents/spring/messaging/CloudEventMessageConverterTests.java
  spring/src/test/java/io/cloudevents/spring/webflux/WebFluxRestControllerTests.java
Labels: enhancement

#313 Javadocs api and core
  amqp/pom.xml
  api/src/main/java/io/cloudevents/CloudEvent.java
  api/src/main/java/io/cloudevents/SpecVersion.java
  api/src/main/java/io/cloudevents/lang/Nullable.java
  api/src/main/java/io/cloudevents/rw/CloudEventDataMapper.java
  api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
  api/src/main/java/io/cloudevents/rw/CloudEventReader.java
  api/src/main/java/io/cloudevents/rw/CloudEventWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventWriterFactory.java
  benchmarks/pom.xml
  core/src/main/java/io/cloudevents/core/CloudEventUtils.java
  core/src/main/java/io/cloudevents/core/data/BytesCloudEventData.java
  core/src/main/java/io/cloudevents/core/data/PojoCloudEventData.java
  core/src/main/java/io/cloudevents/core/extensions/DatarefExtension.java
  core/src/main/java/io/cloudevents/core/extensions/DistributedTracingExtension.java
  core/src/main/java/io/cloudevents/core/extensions/impl/ExtensionUtils.java
  core/src/main/java/io/cloudevents/core/format/EventDeserializationException.java
  core/src/main/java/io/cloudevents/core/format/EventFormat.java
  core/src/main/java/io/cloudevents/core/format/EventSerializationException.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/message/Encoding.java
  core/src/main/java/io/cloudevents/core/message/MessageReader.java
  core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java
  core/src/main/java/io/cloudevents/core/message/StructuredMessageWriter.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseBinaryMessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/GenericStructuredMessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java
  core/src/main/java/io/cloudevents/core/provider/ExtensionProvider.java
  core/src/test/java/io/cloudevents/core/mock/MockStructuredMessageReader.java
  examples/pom.xml
  http/restful-ws-integration-tests/pom.xml
  pom.xml
Labels: documentation

#318 Improve CloudEventHeaderUtils with narrower scoped method
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventHeaderUtils.java
Labels: enhancement

#323 Spring Javadocs
  pom.xml
  spring/src/main/java/io/cloudevents/spring/http/CloudEventHttpUtils.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventContextUtils.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventHeaderUtils.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventMessageConverter.java
  spring/src/main/java/io/cloudevents/spring/mvc/CloudEventHttpMessageConverter.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageReader.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageWriter.java
  spring/src/test/java/io/cloudevents/spring/messaging/CloudEventContextUtilsTests.java
  spring/src/test/java/io/cloudevents/spring/messaging/CloudEventHeaderUtilsTests.java
Labels: documentation

#325 Vert.x 4!
  http/vertx/pom.xml
Labels: dependencies

#320 Http modules javadocs
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/CloudEventsProvider.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/StructuredEncoding.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/Utils.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java
  pom.xml
Labels: documentation

#322 AMQP javadocs
  amqp/src/main/java/io/cloudevents/amqp/ProtonAmqpMessageFactory.java
  amqp/src/test/java/io/cloudevents/amqp/ProtonAmqpMessageFactoryTest.java
  pom.xml
Labels: documentation

#324 Website docs
  README.md
  amqp/README.md
  api/README.md
  core/README.md
  docs/_config.yml
  docs/amqp-proton.md
  docs/api.md
  docs/api.png
  docs/core.md
  docs/http-basic.md
  docs/http-jakarta-restful-ws.md
  docs/http-vertx.md
  docs/index.md
  docs/json-jackson.md
  docs/kafka.md
  docs/rw.png
  docs/spring.md
  formats/json-jackson/README.md
  http/basic/README.md
  http/restful-ws/README.md
  http/vertx/README.md
  kafka/README.md
  spring/README.md
Labels: documentation

#321 Kafka javadocs
  kafka/src/main/java/io/cloudevents/kafka/CloudEventDeserializer.java
  kafka/src/main/java/io/cloudevents/kafka/CloudEventMessageDeserializer.java
  kafka/src/main/java/io/cloudevents/kafka/CloudEventMessageSerializer.java
  kafka/src/main/java/io/cloudevents/kafka/CloudEventSerializer.java
  kafka/src/main/java/io/cloudevents/kafka/KafkaMessageFactory.java
  kafka/src/main/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptor.java
  pom.xml
Labels: documentation

#319 Jackson javadocs
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonCloudEventData.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
  pom.xml
Labels: documentation

#328 Fixed broken links on website
  docs/index.md
Labels: bug, documentation

#331 update AMQP docs
  docs/amqp-proton.md
Labels: documentation

#333 Use scheduler instead of StartupEvent. Resolves #332
  examples/restful-ws-quarkus/pom.xml
  examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/client/UserEventsGenerator.java
  examples/restful-ws-quarkus/src/main/resources/application.properties
Labels: documentation
