Repository cloudevents/sdk-java, pull requests merged in 2020-09, with the labels that each got.

#216 Switch `ZonedDateTime` to `OffsetDateTime`
  api/src/main/java/io/cloudevents/CloudEventAttributes.java
  api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
  api/src/main/java/io/cloudevents/types/Time.java
  api/src/test/java/io/cloudevents/types/TimeTest.java
  core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
  core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
  core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java
  core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  core/src/test/java/io/cloudevents/core/test/Data.java
  formats/json-jackson/src/test/resources/v1/json_data_with_fractional_time.json
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxHttpClientRequestMessageWriterTest.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxHttpServerResponseMessageWriterTest.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
  kafka/src/test/java/io/cloudevents/kafka/KafkaMessageFactoryTest.java
  kafka/src/test/java/io/cloudevents/kafka/KafkaProducerMessageWriterTest.java
Labels: bug

#218 Added a method to remove the extensions
  core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
Labels: enhancement

#206 Vertx 4
  examples/vertx/src/main/java/io/cloudevents/examples/vertx/SampleHTTPClient.java
  http/vertx/README.md
  http/vertx/pom.xml
  http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxWebClientRequestMessageWriterImpl.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxHttpClientRequestMessageWriterTest.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxHttpServerResponseMessageWriterTest.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
Labels: dependencies

#191 Release automation
  core/README.md
  docs/index.md
  scripts/release.md
  scripts/trigger_release.sh
Labels: documentation, enhancement

#224 Fixed some docs
  formats/json-jackson/README.md
  http/restful-ws/README.md
  http/vertx/README.md
Labels: documentation

#225 Generic HTTP bindings
  examples/basic-http/pom.xml
  examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/BasicHttpServer.java
  examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/HttpURLConnectionClient.java
  examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/IOUtils.java
  examples/basic-http/src/main/java/io/cloudevents/examples/http/basic/JettyServer.java
  examples/pom.xml
  http/basic/README.md
  http/basic/pom.xml
  http/basic/src/main/java/io/cloudevents/http/HttpMessageFactory.java
  http/basic/src/main/java/io/cloudevents/http/impl/CloudEventsHeaders.java
  http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageReader.java
  http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageWriter.java
  http/basic/src/test/java/io/cloudevents/http/HttpMessageReaderWriterTest.java
  pom.xml
Labels: enhancement

#229 fix: link in readme
  http/basic/README.md
Labels: bug, documentation

#233 Add CloudEventsProvider to services
  examples/restful-ws-quarkus/src/main/resources/application.properties
  http/restful-ws/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
Labels: enhancement

#235 Added "Used By" section in README.md and added link to "Occurrent" un…
  README.md
Labels: documentation

#236 Add Knative Eventing in "Used By" section
  README.md
Labels: documentation

#237 Renamed methods of *Writers to coerce with the builder apis
  api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
  core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
  core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
  core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
  http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageWriter.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSClientMessageWriter.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageWriter.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxHttpServerResponseMessageWriterImpl.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/impl/VertxWebClientRequestMessageWriterImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/BaseKafkaMessageWriterImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaProducerMessageWriterImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaSerializerMessageWriterImpl.java
Labels: enhancement

#239 Added editorconfig check during the verify phase
  .editorconfig
  README.md
  pom.xml
Labels: enhancement

#248 Release process docs
  .github/workflows/master.yaml
  .github/workflows/pr.yaml
  maintainer_guidelines.md
  scripts/release.md
  scripts/trigger_release.sh
Labels: documentation
