Repository cloudevents/sdk-java, pull requests merged in 2020-11, with the labels that each got.

#256 Cleanup readme
  README.md
Labels: documentation, enhancement

#259 fix: NPE
  formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
Labels: bug

#257 CloudEventUtils.mapData(event, mapper)
  api/src/main/java/io/cloudevents/rw/CloudEventDataMapper.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventUtils.java
  core/src/main/java/io/cloudevents/core/message/MessageReader.java
  core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java
  core/src/test/java/io/cloudevents/core/impl/CloudEventUtilsTest.java
Labels: enhancement

#258 Json mapper
  api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventData.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/MyPojo.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
Labels: enhancement

#260 PartitionKey Kafka Interceptor
  kafka/README.md
  kafka/src/main/java/io/cloudevents/kafka/CloudEventDeserializer.java
  kafka/src/main/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptor.java
  kafka/src/test/java/io/cloudevents/kafka/PartitionKeyExtensionInterceptorTest.java
Labels: enhancement

#263 Improvements to CloudEventReader
  api/src/main/java/io/cloudevents/rw/CloudEventContextReader.java
  api/src/main/java/io/cloudevents/rw/CloudEventReader.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventUtils.java
  core/src/main/java/io/cloudevents/core/message/MessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
  http/basic/src/main/java/io/cloudevents/http/HttpMessageFactory.java
  http/basic/src/test/java/io/cloudevents/http/HttpMessageReaderWriterTest.java
  kafka/src/main/java/io/cloudevents/kafka/CloudEventMessageSerializer.java
Labels: enhancement

#268 feat: new overload for mapper factory
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
Labels: enhancement

#265 Update website deps to latest version
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/favicon.ico
Labels: documentation, enhancement

#261 Moved CloudEventUtils to io.cloudevents.core
  core/src/main/java/io/cloudevents/core/CloudEventUtils.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
  core/src/main/java/io/cloudevents/core/message/MessageReader.java
  core/src/main/java/io/cloudevents/core/message/MessageWriter.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/CloudEventUtilsTest.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
  kafka/src/test/java/io/cloudevents/kafka/CloudEventMessageSerializerTest.java
Labels: enhancement

#267 Javadoc'ed + Cleanup of the api module
  api/src/main/java/io/cloudevents/CloudEventData.java
  api/src/main/java/io/cloudevents/CloudEventExtensions.java
  api/src/main/java/io/cloudevents/Extension.java
  api/src/main/java/io/cloudevents/SpecVersion.java
  api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
  api/src/main/java/io/cloudevents/rw/CloudEventReader.java
  api/src/main/java/io/cloudevents/rw/CloudEventWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventWriterFactory.java
  api/src/main/java/io/cloudevents/types/Time.java
  api/src/test/java/io/cloudevents/SpecVersionTest.java
  api/src/test/java/io/cloudevents/types/TimeTest.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v03/V1ToV03AttributesConverter.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/V03ToV1AttributesConverter.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventData.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
Labels: documentation, enhancement

#275 Build javadoc in all profiles
  pom.xml
Labels: documentation, enhancement

#279 Fix getAttribute("datacontentencoding") in CloudEventV03
  core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
  core/src/test/java/io/cloudevents/core/v03/CloudEventBuilderTest.java
Labels: bug, enhancement

#270 [#30] Implement AMQP 1.0 transport binding
  amqp/pom.xml
  amqp/src/main/java/io/cloudevents/amqp/ProtonAmqpMessageFactory.java
  amqp/src/main/java/io/cloudevents/amqp/impl/AmqpConstants.java
  amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpBinaryMessageReader.java
  amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpMessageWriter.java
  amqp/src/test/java/io/cloudevents/amqp/ProtonAmqpMessageFactoryTest.java
  amqp/src/test/java/io/cloudevents/amqp/ProtonAmqpMessageWriterTest.java
  pom.xml
Labels: enhancement

#281 CloudEventBuilder should fail when providing an invalid extension name
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
Labels: bug

#284 Add sources plugin to Maven build
  pom.xml
Labels: enhancement

#286 Introduce CloudEventDataMapper.identity()
  api/src/main/java/io/cloudevents/rw/CloudEventDataMapper.java
  api/src/main/java/io/cloudevents/rw/CloudEventReader.java
  core/src/main/java/io/cloudevents/core/CloudEventUtils.java
  core/src/main/java/io/cloudevents/core/format/EventFormat.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
  core/src/main/java/io/cloudevents/core/impl/CloudEventReaderAdapter.java
  core/src/main/java/io/cloudevents/core/message/MessageReader.java
  core/src/main/java/io/cloudevents/core/message/StructuredMessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseStructuredMessageReader.java
  core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
  core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java
  kafka/src/test/java/io/cloudevents/kafka/CloudEventDeserializerTest.java
Labels: enhancement

#292 Update dataref extension value to string to be supported by BaseCloud…
  core/src/main/java/io/cloudevents/core/extensions/DatarefExtension.java
  core/src/test/java/io/cloudevents/core/extensions/DatarefExtensionTest.java
Labels: bug

#280 Removing ContextAttributes enums
  core/src/main/java/io/cloudevents/core/v03/CloudEventV03.java
  core/src/main/java/io/cloudevents/core/v03/ContextAttributes.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java
  core/src/main/java/io/cloudevents/core/v1/ContextAttributes.java
Labels: enhancement

#287 CloudEventAttributesWriter/CloudEventExtensionsWriter accepts only non null values
  api/src/main/java/io/cloudevents/rw/CloudEventAttributesWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventExtensionsWriter.java
  core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
Labels: bug

#289 Move PojoCloudEventData in core
  core/src/main/java/io/cloudevents/core/data/PojoCloudEventData.java
  core/src/test/java/io/cloudevents/core/data/PojoCloudEventDataTest.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventData.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/PojoCloudEventDataMapper.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/PojoCloudEventDataMapperTest.java
Labels: enhancement

#282 [Refactoring] Aggregate widely used constants.
  amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpMessageWriter.java
  amqp/src/test/java/io/cloudevents/amqp/ProtonAmqpMessageFactoryTest.java
  core/src/main/java/io/cloudevents/core/message/impl/BaseGenericBinaryMessageReaderImpl.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  http/basic/src/main/java/io/cloudevents/http/impl/CloudEventsHeaders.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaHeaders.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaProducerMessageWriterImpl.java
Labels: cleanup, enhancement

#288 Restful WS Spring boot example
  examples/pom.xml
  examples/restful-ws-spring-boot/README.md
  examples/restful-ws-spring-boot/pom.xml
  examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/Application.java
  examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/JerseyConfiguration.java
  examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/MainResource.java
  examples/restful-ws-spring-boot/src/main/java/io/cloudevents/examples/springboot/User.java
Labels: documentation

#294 Add AMQP example
  examples/amqp-proton/README.md
  examples/amqp-proton/pom.xml
  examples/amqp-proton/src/main/java/io/cloudevents/examples/amqp/vertx/AmqpClient.java
  examples/amqp-proton/src/main/java/io/cloudevents/examples/amqp/vertx/AmqpServer.java
  examples/pom.xml
Labels: documentation

#295 Removed some travis leftovers
  README.md
  pom.xml
Labels: documentation

#290 Pom cleanup
  api/pom.xml
  core/pom.xml
  formats/json-jackson/pom.xml
  http/basic/pom.xml
  http/restful-ws-integration-tests/pom.xml
  http/restful-ws/pom.xml
  http/vertx/pom.xml
Labels: cleanup

#291 Add method `BytesCloudEventData#wrap`
  amqp/src/main/java/io/cloudevents/amqp/impl/ProtonAmqpBinaryMessageReader.java
  core/src/main/java/io/cloudevents/core/data/BytesCloudEventData.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/mock/CSVFormat.java
  core/src/test/java/io/cloudevents/core/mock/MockBinaryMessageWriter.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  http/basic/src/main/java/io/cloudevents/http/impl/HttpMessageReader.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/BinaryRestfulWSMessageReaderImpl.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/impl/BinaryVertxMessageReaderImpl.java
  kafka/src/main/java/io/cloudevents/kafka/impl/KafkaBinaryMessageReaderImpl.java
Labels: enhancement

#299 Bump Vertx from 4.0.0.Beta1 to 4.0.0.CR2
  http/vertx/pom.xml
Labels: dependencies

#298 Examples readme
  README.md
  examples/README.md
  examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/client/UserEventsGenerator.java
  examples/restful-ws-quarkus/src/main/java/io/cloudevents/examples/quarkus/resources/UserResource.java
Labels: documentation, enhancement

#300 Simplify BaseCloudEventBuilder constructor
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
Labels: cleanup

#303 add README.md for AMQP binding
  amqp/README.md
Labels: documentation

#277 Remove UnknownEncodingMessageReader and replace with exceptions #262
  amqp/src/main/java/io/cloudevents/amqp/ProtonAmqpMessageFactory.java
  api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
  core/src/main/java/io/cloudevents/core/message/Encoding.java
  core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java
  core/src/main/java/io/cloudevents/core/message/impl/UnknownEncodingMessageReader.java
  core/src/test/java/io/cloudevents/core/message/impl/MessageUtilsTest.java
  http/basic/src/main/java/io/cloudevents/http/HttpMessageFactory.java
  http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/RestfulWSMessageFactory.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java
  kafka/src/main/java/io/cloudevents/kafka/CloudEventSerializer.java
  kafka/src/main/java/io/cloudevents/kafka/KafkaMessageFactory.java
Labels: enhancement

#304 Bump junit5
  pom.xml
Labels: dependencies

#306 Fix NPE on null body with structured message
  core/src/main/java/io/cloudevents/core/message/impl/GenericStructuredMessageReader.java
  http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
Labels: bug

#307 [Vertx] Fail promise on create reader exception
  http/vertx/src/main/java/io/cloudevents/http/vertx/VertxMessageFactory.java
  http/vertx/src/test/java/io/cloudevents/http/vertx/VertxMessageFactoryTest.java
Labels: bug

#312 HTTP converters for CloudEvent in Spring
  pom.xml
  spring/README.md
  spring/pom.xml
  spring/src/main/java/io/cloudevents/spring/http/CloudEventHttpUtils.java
  spring/src/main/java/io/cloudevents/spring/http/CloudEventsHeaders.java
  spring/src/main/java/io/cloudevents/spring/http/package-info.java
  spring/src/main/java/io/cloudevents/spring/mvc/CloudEventHttpMessageConverter.java
  spring/src/main/java/io/cloudevents/spring/mvc/package-info.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageReader.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageWriter.java
  spring/src/main/java/io/cloudevents/spring/webflux/package-info.java
  spring/src/test/java/io/cloudevents/spring/mvc/MvcRestControllerTests.java
  spring/src/test/java/io/cloudevents/spring/webflux/WebFluxRestControllerTests.java
Labels: enhancement

#314 Add a Spring sample with webflux
  examples/README.md
  examples/pom.xml
  examples/spring-reactive/README.md
  examples/spring-reactive/pom.xml
  examples/spring-reactive/src/main/java/io/cloudevents/examples/spring/DemoApplication.java
  examples/spring-reactive/src/main/java/io/cloudevents/examples/spring/Foo.java
  examples/spring-reactive/src/test/java/io/cloudevents/examples/spring/DemoApplicationTests.java
Labels: documentation
