Repository cloudevents/sdk-java, pull requests merged in 2021-04, with the labels that each got.

#366 CloudEvents attribute names SHOULD NOT exceed 20 chars
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
Labels: bug

#367 Avoid allocating an array on extension validation
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
Labels: bug

#348 formats: Add support for protobuf format
  README.md
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  docs/index.md
  docs/protobuf.md
  formats/protobuf/README.md
  formats/protobuf/pom.xml
  formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoCloudEventData.java
  formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoDataWrapper.java
  formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoDeserializer.java
  formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtoSerializer.java
  formats/protobuf/src/main/java/io/cloudevents/protobuf/ProtobufFormat.java
  formats/protobuf/src/main/proto/spec.proto
  formats/protobuf/src/main/resources/META-INF/services/io.cloudevents.core.format.EventFormat
  formats/protobuf/src/test/java/io/cloudevents/protobuf/ProtoMessageDataTest.java
  formats/protobuf/src/test/java/io/cloudevents/protobuf/ProtobufFormatTest.java
  formats/protobuf/src/test/java/io/cloudevents/protobuf/TestProto.java
  formats/protobuf/src/test/proto/test.proto
  formats/protobuf/src/test/resources/README.md
  formats/protobuf/src/test/resources/v03/min.proto.json
  formats/protobuf/src/test/resources/v1/binary_ext.proto.json
  formats/protobuf/src/test/resources/v1/json_data.proto.json
  formats/protobuf/src/test/resources/v1/json_data_with_ext.proto.json
  formats/protobuf/src/test/resources/v1/min.proto.json
  formats/protobuf/src/test/resources/v1/text_data.proto.json
  formats/protobuf/src/test/resources/v1/xml_data.proto.json
  pom.xml
Labels: enhancement

#380 CESQL Benchmark
  benchmarks/pom.xml
  benchmarks/src/main/java/io/cloudevents/bench/sql/CompileBenchmark.java
  benchmarks/src/main/java/io/cloudevents/bench/sql/RunBenchmark.java
Labels: performance
