Repository cloudevents/sdk-java, pull requests merged in 2021-03, with the labels that each got.

#350 Allow user to enumerate supported content types
  core/src/main/java/io/cloudevents/core/provider/EventFormatProvider.java
  core/src/test/java/io/cloudevents/core/provider/EventFormatProviderTest.java
Labels: enhancement

#354 Regularize copyright headers
  spring/src/main/java/io/cloudevents/spring/codec/package-info.java
  spring/src/main/java/io/cloudevents/spring/http/CloudEventHttpUtils.java
  spring/src/main/java/io/cloudevents/spring/http/CloudEventsHeaders.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventContextUtils.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventMessageConverter.java
  spring/src/main/java/io/cloudevents/spring/messaging/CloudEventsHeaders.java
  spring/src/main/java/io/cloudevents/spring/messaging/MessageBinaryMessageReader.java
  spring/src/main/java/io/cloudevents/spring/messaging/MessageBuilderMessageWriter.java
  spring/src/main/java/io/cloudevents/spring/mvc/CloudEventHttpMessageConverter.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageReader.java
  spring/src/main/java/io/cloudevents/spring/webflux/CloudEventHttpMessageWriter.java
Labels: documentation

#355 Flesh out the docs in the Spring module a bit
  docs/spring.md
Labels: documentation

#353 Introduced support for Binary attribute types.
  api/src/main/java/io/cloudevents/CloudEventExtension.java
  api/src/main/java/io/cloudevents/rw/CloudEventContextWriter.java
  core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEvent.java
  core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/impl/BaseCloudEventBuilderTest.java
  core/src/test/java/io/cloudevents/core/test/Data.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
  formats/json-jackson/src/test/resources/v1/binary_attr.json
Labels: enhancement

#358 Specification Compliant handling of numeric context attributes
  api/src/main/java/io/cloudevents/rw/CloudEventContextWriter.java
  api/src/main/java/io/cloudevents/rw/CloudEventRWException.java
  core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java
  core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java
  core/src/test/java/io/cloudevents/core/test/Data.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventDeserializer.java
  formats/json-jackson/src/main/java/io/cloudevents/jackson/CloudEventSerializer.java
  formats/json-jackson/src/test/java/io/cloudevents/jackson/JsonFormatTest.java
  formats/json-jackson/src/test/resources/v03/fail_numeric_decimal.json
  formats/json-jackson/src/test/resources/v03/fail_numeric_long.json
  formats/json-jackson/src/test/resources/v1/fail_numeric_decimal.json
  formats/json-jackson/src/test/resources/v1/fail_numeric_long.json
  formats/json-jackson/src/test/resources/v1/numeric_ext.json
Labels: bug

#362 Throw exceptions when attempting to handle unsupported CloudEvent formats
  core/src/main/java/io/cloudevents/core/message/impl/MessageUtils.java
  core/src/test/java/io/cloudevents/core/message/impl/MessageUtilsTest.java
Labels: bug
