Repository cloudevents/sdk-java, pull requests merged in 2021-05, with the labels that each got.

#384 Use correct encoding for structured event
  examples/kafka/src/main/java/io/cloudevents/examples/kafka/SampleProducer.java
Labels: bug, documentation

#381 Fix like expression
  sql/src/main/java/io/cloudevents/sql/impl/expressions/LikeExpression.java
  sql/src/test/resources/tck/like_expression.yaml
Labels: bug

#385 [2.1] Fix like expression
  sql/src/main/java/io/cloudevents/sql/impl/expressions/LikeExpression.java
  sql/src/test/resources/tck/like_expression.yaml
Labels: bug

#394 Update the link to http4k Cloud Events module.
  README.md
Labels: documentation
